name: PBL4-BE CI/CD

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build
              run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/pbl4-be:${{ github.sha }} .

            - name: Push image to docker hub
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/pbl4-be:${{ github.sha }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to the VM Server
              run: |
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa
                  chmod 600 /tmp/id_rsa

                  eval $(ssh-agent -s)
                  ssh-add /tmp/id_rsa
                  ssh -v -i /tmp/id_rsa -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} << "EOF"
                      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pbl4-be:${{ github.sha }}
                      docker stop pbl4-be || true
                      docker rm pbl4-be || true
                      echo "${{ secrets.ENV_FILE }}" > .env
                      docker run -d -p 3000:3000 --env-file .env --name pbl4-be ${{ secrets.DOCKERHUB_USERNAME }}/pbl4-be:${{ github.sha }}

                      docker image prune -a -f
                      docker system prune -f                 
                  EOF
